name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Update Rust
        run: |
          rustup update
      - name: Format
        run: cargo fmt && git diff --exit-code
      - name: Lint
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings

  docs:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.12"
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.1"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Build docs
        run: |
          uv run --python=${{ env.PYTHON_VERSION }} --group=docs mkdocs build --strict

  test:
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - uses: astral-sh/setup-uv@v7
      with:
        version: "0.11.1"
        python-version: ${{ matrix.python }}


    - name: Install just and grcov
      run: |
        cargo install just grcov

    - name: Build
      run: |
        just develop
        just protoc

    - name: Run coverage
      run: just coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./lcov.info,./coverage.xml
        fail_ci_if_error: true

  all-tests-pass:
    if: always()

    needs:
    - lint
    - docs
    - test

    runs-on: ubuntu-latest

    steps:
      - name: check test jobs
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
